# Generated by Django 6.0.5 on 2026-05-25 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_create_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('stack_tecnologico', models.CharField(max_length=300)),
                ('score_cumplimiento', models.IntegerField(default=100)),
                ('dictamen', models.CharField(choices=[('viable', 'Viable'), ('con_riesgos', 'Viable con Riesgos'), ('no_viable', 'No Viable')], default='viable', max_length=20)),
                ('analisis_cualitativo_ia', models.TextField(blank=True, help_text='Comentarios semánticos generados por la IA de Gemini')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RiesgoDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('gravedad', models.CharField(choices=[('critica', 'Crítica'), ('media', 'Media'), ('leve', 'Leve')], max_length=15)),
                ('principio_ley_afectada', models.CharField(help_text='Principio UNAS o Ley Peruana afectada', max_length=150)),
                ('sugerencia_mitigacion', models.TextField(blank=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='forum.proyectoauditoria')),
            ],
        ),
    ]
